/*
 * generated by Xtext
 */
package org.yazgel.titan.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TitanRuntimeModule extends org.yazgel.titan.xtext.AbstractTitanRuntimeModule {

}
