/*
* generated by Xtext
*/
package org.yazgel.titan.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.yazgel.titan.xtext.services.TitanGrammarAccess;

public class TitanParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TitanGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.yazgel.titan.xtext.parser.antlr.internal.InternalTitanParser createParser(XtextTokenStream stream) {
		return new org.yazgel.titan.xtext.parser.antlr.internal.InternalTitanParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Module";
	}
	
	public TitanGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TitanGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
