/*
 * generated by Xtext
 */
package org.yazgel.titan.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TitanUiModule extends org.yazgel.titan.xtext.ui.AbstractTitanUiModule {
	public TitanUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
