/*
 * generated by Xtext
 */
package org.yazgel.titan.xtext.ui.contentassist

import org.yazgel.titan.xtext.ui.contentassist.AbstractTitanProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class TitanProposalProvider extends AbstractTitanProposalProvider {
}
