/*
* generated by Xtext
*/
package org.yazgel.titan.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TitanUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.yazgel.titan.xtext.ui.internal.TitanActivator.getInstance().getInjector("org.yazgel.titan.xtext.Titan");
	}
	
}
