/*
 * generated by Xtext
 */
package org.yazgel.titan.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.yazgel.titan.xtext.ui.internal.TitanActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TitanExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TitanActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TitanActivator.getInstance().getInjector(TitanActivator.ORG_YAZGEL_TITAN_XTEXT_TITAN);
	}
	
}
